-- Supabase schema for Atelie da Escola

create table if not exists public.categories (
	id bigint generated by default as identity primary key,
	name text not null,
	slug text not null unique,
	color text not null default '#9B5DE5',
	active boolean not null default true,
	featured boolean not null default false,
	badge_label text not null default '',
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.products (
	id bigint generated by default as identity primary key,
	name text not null,
	description text not null default '',
	price numeric(12,2) not null default 0,
	original_price numeric(12,2),
	image_url text not null default '',
	download_url text not null default '',
	category_id bigint references public.categories(id) on delete set null,
	active boolean not null default true,
	featured boolean not null default false,
	tags jsonb not null default '[]'::jsonb,
	product_type text not null default 'individual',
	is_kit boolean not null default false,
	page_size text not null default '',
	paper_type text not null default '',
	kit_items jsonb not null default '[]'::jsonb,
	panel_sizes jsonb not null default '[]'::jsonb,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.orders (
	id bigint generated by default as identity primary key,
	order_code text not null unique,
	customer_name text not null default '',
	customer_email text not null,
	customer_cpf text,
	customer_phone text,
	total_amount numeric(12,2) not null default 0,
	status text not null default 'pending',
	payment_status text not null default 'pending',
	payment_id text,
	preference_id text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	completed_at timestamptz
);

create table if not exists public.order_items (
	id bigint generated by default as identity primary key,
	order_id bigint not null references public.orders(id) on delete cascade,
	product_id bigint not null references public.products(id) on delete restrict,
	product_name text not null,
	unit_price numeric(12,2) not null default 0,
	quantity integer not null default 1,
	total_price numeric(12,2) not null default 0,
	created_at timestamptz not null default now()
);

create table if not exists public.download_tokens (
	id bigint generated by default as identity primary key,
	token text not null unique,
	order_id bigint not null references public.orders(id) on delete cascade,
	product_id bigint not null references public.products(id) on delete cascade,
	product_name text not null default '',
	used boolean not null default false,
	used_at timestamptz,
	expires_at timestamptz,
	created_at timestamptz not null default now()
);

create table if not exists public.download_logs (
	id bigint generated by default as identity primary key,
	order_id bigint references public.orders(id) on delete set null,
	product_id bigint references public.products(id) on delete set null,
	token text not null default '',
	ip_address text not null default '',
	user_agent text not null default '',
	downloaded_at timestamptz not null default now()
);

create table if not exists public.profiles (
	id bigint generated by default as identity primary key,
	email text not null unique,
	display_name text not null default '',
	role text not null default 'customer',
	provider text not null default 'email',
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.user_products (
	id bigint generated by default as identity primary key,
	email text not null,
	product_ids jsonb not null default '[]'::jsonb,
	purchases jsonb not null default '[]'::jsonb,
	updated_at timestamptz not null default now(),
	created_at timestamptz not null default now()
);

create table if not exists public.settings (
	setting_key text primary key,
	setting_value jsonb,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.page_views (
	id bigint generated by default as identity primary key,
	page_path text not null,
	session_id text,
	user_agent text not null default '',
	referrer text not null default '',
	created_at timestamptz not null default now()
);

create index if not exists products_active_created_at_idx on public.products (active, created_at desc);
create index if not exists products_category_idx on public.products (category_id);
create index if not exists orders_customer_email_idx on public.orders (customer_email);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists download_tokens_token_idx on public.download_tokens (token);
create index if not exists download_tokens_order_id_idx on public.download_tokens (order_id);
create index if not exists download_logs_product_id_idx on public.download_logs (product_id);
create index if not exists page_views_created_at_idx on public.page_views (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
before update on public.settings
for each row execute function public.set_updated_at();
