// ════════════════════════════════════════════════════════════════════
// Schemas dos recursos CRUD do admin — regra B1, item P2.2.
//
// ── PRINCÍPIO, O MESMO DE validation/index.js ───────────────────────
// Nada nos LIMITES muda. Todo teto aqui replica exatamente o que os cinco
// handlers já aplicavam à mão. A regra B1 é sobre ONDE a validação acontece,
// não sobre endurecer o contrato — mudar as duas coisas de uma vez tornaria
// impossível saber qual delas quebrou a tela da dona da loja.
//
// ── A ÚNICA EXCEÇÃO, E POR QUE ELA VALE ─────────────────────────────
// O `id`. Antes era `String(body.id || '').trim()` e seguia direto para o
// filtro `id=eq.<valor>` do PostgREST. Validar o FORMATO antes de o valor ser
// interpolado ali é a defesa que o comentário de `common.schemas.js:UUID_RE`
// descreve, e é por isso que aquele primitivo existe. Aqui ele ganha uso.
//
// ⚠️ E ele NÃO é uuid em todo lugar: `coupons.id` é
// `bigint generated by default as identity` (supabase/schema.sql:208),
// enquanto categories, products, orders e profiles são `uuid`. Um schema de
// `id` único para os cinco quebraria os cupons em produção sem barulho nenhum
// em dev — conferido no schema, não suposto.
// ════════════════════════════════════════════════════════════════════

const { z } = require('zod');

const { cleanText, uuid } = require('./common.schemas');

// ── Primitivos de identificador ──────────────────────────────────────

/** `id` das tabelas com PK uuid: categories, products, orders, profiles. */
const uuidId = uuid;

/** `id` de `coupons`, que é bigint identity. Aceita número ou string numérica. */
const bigintId = z
  .union([z.number(), z.string()])
  .transform((value) => String(value).trim())
  .refine((value) => /^[1-9]\d{0,18}$/.test(value), { error: 'Identificador inválido.' });

/**
 * Slug derivado do nome, nunca recebido do cliente.
 *
 * Fica aqui e não em `common.schemas.js` porque é forma de SAÍDA da
 * normalização do admin, e não entrada de borda como `uuid` ou `email`.
 */
const slug = z
  .string()
  .trim()
  .toLowerCase()
  .refine((value) => /^[a-z0-9-]+$/.test(value), { error: 'Slug inválido.' });

/**
 * Valor monetário do LADO ADMIN (preço de produto, total de pedido).
 *
 * Diferente de `clientPrice`: aquele é prévia vinda do navegador e nunca é
 * fonte de verdade para cobrança; este É gravado no banco. O teto de 1.000.000
 * é o mesmo — um valor acima disso é digitação errada, não catálogo.
 */
const money = z.coerce
  .number({ error: 'Valor inválido.' })
  .min(0, { error: 'Valor não pode ser negativo.' })
  .max(1_000_000, { error: 'Valor acima do limite.' });

function normalizeSlug(value) {
  return (
    String(value || '')
      .trim()
      .toLowerCase()
      .normalize('NFD')
      .replaceAll(/[\u0300-\u036f]/g, '')
      .replaceAll(/[^a-z0-9]+/g, '-')
      .replaceAll(/^-+|-+$/g, '') || 'sem-categoria'
  );
}

// ── Categorias ───────────────────────────────────────────────────────

const UUID_LOOKING_NAME = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const categoryName = z
  .unknown()
  .transform(cleanText)
  .refine((value) => value.length > 0, { error: 'Nome da categoria é obrigatório.' })
  // Mantido do handler: colar um ID no campo nome era erro real de operação, e
  // o resultado era uma categoria chamada "8f3c…" no menu da loja.
  .refine((value) => !UUID_LOOKING_NAME.test(value), {
    error: 'Nome inválido: não cole IDs no campo nome.',
  })
  .refine((value) => value.length >= 2 && value.length <= 60, {
    error: 'Nome deve ter entre 2 e 60 caracteres.',
  });

const categoryCreateSchema = z.object({
  name: categoryName,
  color: z.string().trim().optional(),
  active: z.boolean().optional(),
  featured: z.boolean().optional(),
});

const categoryUpdateSchema = z.object({
  id: uuidId,
  name: categoryName.optional(),
  color: z.string().trim().optional(),
  active: z.boolean().optional(),
  featured: z.boolean().optional(),
});

// ── Cupons ───────────────────────────────────────────────────────────

const couponCode = z
  .unknown()
  .transform((value) =>
    String(value ?? '')
      .trim()
      .toUpperCase()
      .replaceAll(/\s+/g, '')
      .slice(0, 64),
  )
  .refine((value) => value.length > 0, { error: 'Código do cupom é obrigatório.' })
  .refine((value) => value.length >= 3, { error: 'Código deve ter ao menos 3 caracteres.' })
  .refine((value) => /^[A-Z0-9._-]+$/.test(value), {
    error: 'Código só pode ter letras, números, ponto, hífen e underscore.',
  });

const discountType = z.enum(['percent', 'fixed'], {
  error: 'Tipo de desconto deve ser percentual ou valor fixo.',
});

/** Data opcional: vazio vira `null`; texto que não é data vira erro. */
const optionalDate = z
  .union([z.string(), z.number(), z.date(), z.null()])
  .transform((value) => {
    if (value === null || String(value).trim() === '') return null;
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? Number.NaN : date.toISOString();
  })
  .refine((value) => value === null || typeof value === 'string', {
    error: 'Data de validade inválida.',
  });

/** Número opcional não-negativo: vazio ou não-numérico vira `null`. */
const optionalNonNegative = z.union([z.string(), z.number(), z.null()]).transform((value) => {
  if (value === null || String(value).trim() === '') return null;
  const num = Number(value);
  return Number.isFinite(num) ? num : null;
});

const couponCreateSchema = z
  .object({
    code: couponCode,
    discountType: discountType.optional(),
    discountValue: z.coerce.number({ error: 'Valor do desconto deve ser maior que zero.' }),
    validFrom: optionalDate.optional(),
    validUntil: optionalDate.optional(),
    maxUses: optionalNonNegative.optional(),
    minOrderAmount: optionalNonNegative.optional(),
    active: z.boolean().optional(),
  })
  .refine((data) => Number.isFinite(data.discountValue) && data.discountValue > 0, {
    error: 'Valor do desconto deve ser maior que zero.',
    path: ['discountValue'],
  })
  .refine((data) => !((data.discountType || 'percent') === 'percent' && data.discountValue > 100), {
    error: 'Desconto percentual não pode passar de 100%.',
    path: ['discountValue'],
  });

// ── Produtos ─────────────────────────────────────────────────────────

const productCreateSchema = z.object({
  name: z
    .unknown()
    .transform(cleanText)
    .refine((value) => value.length > 0, { error: 'name e price válidos são obrigatórios' }),
  price: money.refine((value) => value > 0, { error: 'name e price válidos são obrigatórios' }),
});

/**
 * PATCH de produto: só `active` e `featured`, e ao menos um dos dois.
 *
 * O handler já rejeitava payload vazio; a diferença é que a regra agora está
 * DECLARADA em vez de derivada de `Object.keys(payload).length === 1`, que é
 * o tipo de condição que ninguém consegue ler sem executar mentalmente.
 */
const productPatchSchema = z
  .object({
    id: uuidId,
    active: z.boolean().optional(),
    featured: z.boolean().optional(),
  })
  .refine((data) => data.active !== undefined || data.featured !== undefined, {
    error: 'Nenhum campo suportado para atualização parcial.',
  });

// ── Pedidos ──────────────────────────────────────────────────────────

const orderUpdateSchema = z
  .object({
    id: uuidId,
    status: z.string().trim().optional(),
    paymentStatus: z.string().trim().optional(),
    customerName: z.string().trim().optional(),
    customerEmail: z.string().trim().toLowerCase().optional(),
    totalAmount: money.optional(),
  })
  .refine(
    (data) =>
      data.status !== undefined ||
      data.paymentStatus !== undefined ||
      data.customerName !== undefined ||
      data.customerEmail !== undefined ||
      data.totalAmount !== undefined,
    { error: 'Nenhum campo válido para atualização.' },
  );

// ── Usuários ─────────────────────────────────────────────────────────

// Roles que este endpoint pode ATRIBUIR. 'admin'/'master' são deliberadamente
// omitidos: promover a admin por aqui seria escalada de privilégio, já que a
// autorização do painel é decidida por `profiles.role`.
const ASSIGNABLE_ROLES = Object.freeze(['customer', 'cliente', 'seller', 'vendedor']);

const userUpdateSchema = z
  .object({
    id: uuidId,
    name: z.string().trim().optional(),
    role: z
      .string()
      .trim()
      .toLowerCase()
      .refine((value) => ASSIGNABLE_ROLES.includes(value), {
        error: 'Role inválida. Não é permitido atribuir admin/master por este endpoint.',
      })
      .optional(),
    provider: z.string().trim().toLowerCase().optional(),
  })
  .refine(
    (data) => data.name !== undefined || data.role !== undefined || data.provider !== undefined,
    { error: 'Nenhum campo válido para atualização.' },
  );

module.exports = {
  ASSIGNABLE_ROLES,
  bigintId,
  categoryCreateSchema,
  categoryUpdateSchema,
  couponCreateSchema,
  money,
  normalizeSlug,
  orderUpdateSchema,
  productCreateSchema,
  productPatchSchema,
  slug,
  userUpdateSchema,
  uuidId,
};
