-- ════════════════════════════════════════════════════════════════════
-- Phase 4 — admin_audit_log (regra I1)
--
-- Registra ações de ESCRITA do painel admin (create/update/patch/delete
-- de produtos, categorias, cupons, pedidos, usuários e settings).
--
-- ⚠ A sessão admin é opaca: o cookie HMAC carrega só `sub:'admin'`, sem
--   identidade individual (ver lib/admin-session.js). Por isso `admin_id`
--   guarda o valor fixo 'admin' + o IP de origem para rastreio. Quando o
--   login admin com Google (§3.7) entrar, dá pra preencher admin_id real.
--
-- RLS habilitada SEM policies → service-role only (mesma estratégia de
-- security_events / download_logs). Idempotente.
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id text not null default 'admin',
  action text not null,            -- create | update | patch | delete
  target_type text not null,       -- product | category | coupon | order | user | setting
  target_id text,
  before jsonb,
  after jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_type, created_at desc);
create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

alter table public.admin_audit_log enable row level security;
-- Sem policies — service role bypassa, anon/authenticated não enxergam.

comment on table public.admin_audit_log is
  'Auditoria de ações de escrita do painel admin (regra I1). Service role only.';
