-- ════════════════════════════════════════════════════════════════════
-- Phase 0 — Mensuração do funil
-- Adiciona tabela analytics_events (eventos canônicos do funil)
-- e coluna orders.attribution_data (UTMs persistidas por compra).
-- Idempotente: pode ser rodado múltiplas vezes sem efeito colateral.
-- ════════════════════════════════════════════════════════════════════

-- ─── 1. Coluna de atribuição em orders ────────────────────────────
alter table public.orders
  add column if not exists attribution_data jsonb not null default '{}'::jsonb;

create index if not exists orders_attribution_source_idx
  on public.orders ((attribution_data->>'utm_source'));


-- ─── 2. Tabela de eventos canônicos do funil ──────────────────────
-- Granularidade: 1 linha = 1 evento (view_item, add_to_cart, etc.)
-- Sem PII: customer_email é opcional e só vai para eventos backend.
-- Banco real usa uuid para orders.id e products.id (divergência do schema.sql
-- legado, ver docs/ARCHITECTURE.md). FKs precisam casar.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text not null default '',
  customer_email text,
  order_id uuid references public.orders(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  properties jsonb not null default '{}'::jsonb,
  source text not null default 'web',
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_created_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_session_idx
  on public.analytics_events (session_id, created_at desc);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);


-- ─── 3. RLS: anon pode INSERT (essential events), nenhum SELECT ───
-- SELECT só pelo service role (backend admin). Mesma estratégia de
-- download_tokens/download_logs/settings, conforme docs/SECURITY.md §3.
alter table public.analytics_events enable row level security;

drop policy if exists analytics_events_public_insert on public.analytics_events;
create policy analytics_events_public_insert
  on public.analytics_events for insert
  to anon, authenticated
  with check (
    -- Whitelist de eventos canônicos aceitos do client
    event_name in (
      'view_item',
      'add_to_cart',
      'begin_checkout',
      'remove_from_cart',
      'view_cart',
      'view_catalog'
    )
    -- Bloqueia tentativa de gravar order_id arbitrário do client
    and order_id is null
    -- Bloqueia gravar email a partir do client (PII)
    and customer_email is null
  );

-- Nenhuma policy de SELECT: service role bypassa, anon/authenticated
-- não enxergam nada. Funil é renderizado pelo backend.
