-- ════════════════════════════════════════════════════════════════════
-- Phase 2 — UX e conversão
-- Adiciona:
--   1. products.faq + products.reviews + products.benefits (jsonb)
--   2. tabela coupons (cupons de desconto, server-side validation)
--   3. tabela abandoned_carts (recuperação de carrinho — Fase 3 envia)
--   4. orders.coupon_code + orders.discount_amount
-- Idempotente. Aplicar com SQL Editor ou `npm run supabase:db:push`.
-- ════════════════════════════════════════════════════════════════════

-- ─── 1. Colunas conversion-oriented em products ───────────────────
alter table public.products
  add column if not exists faq jsonb not null default '[]'::jsonb,
  add column if not exists reviews jsonb not null default '[]'::jsonb,
  add column if not exists benefits jsonb not null default '[]'::jsonb;

-- ─── 2. Tabela coupons ────────────────────────────────────────────
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  valid_from timestamptz,
  valid_until timestamptz,
  max_uses integer,
  used_count integer not null default 0,
  -- applies_to: { category_ids: [...], product_ids: [...] } opcional;
  -- se vazio/nulo aplica a tudo
  applies_to jsonb not null default '{}'::jsonb,
  -- min_order_amount: valor mínimo do pedido para o cupom ser válido
  min_order_amount numeric(12,2),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coupons_code_idx on public.coupons (code);
create index if not exists coupons_active_idx on public.coupons (active);

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at
  before update on public.coupons
  for each row execute function public.set_updated_at();

-- RLS: cupons NÃO são lidos diretamente pelo browser. Toda validação
-- passa por /api/validate-coupon usando service role. Defesa em
-- profundidade: bloqueia leitura/escrita por anon/authenticated.
alter table public.coupons enable row level security;
-- Sem policies = sem acesso para anon/authenticated. Service role bypassa.


-- ─── 3. Tabela abandoned_carts ────────────────────────────────────
-- Cliente digita e-mail no checkout → backend grava aqui. Em ~1h e
-- ~24h um job (Fase 3) envia e-mail de recuperação. Limpa quando o
-- cliente conclui a compra ou após 7 dias.
create table if not exists public.abandoned_carts (
  id bigint generated by default as identity primary key,
  email text not null,
  session_id text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  recovered_at timestamptz,
  reminder_sent_at timestamptz,
  attribution_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists abandoned_carts_email_session_idx
  on public.abandoned_carts (lower(email), coalesce(session_id, ''));

create index if not exists abandoned_carts_created_at_idx
  on public.abandoned_carts (created_at desc);

drop trigger if exists abandoned_carts_set_updated_at on public.abandoned_carts;
create trigger abandoned_carts_set_updated_at
  before update on public.abandoned_carts
  for each row execute function public.set_updated_at();

-- RLS: anon pode INSERT/UPSERT para salvar o próprio carrinho.
-- Nenhum SELECT — backend lê via service role para enviar e-mail.
alter table public.abandoned_carts enable row level security;

drop policy if exists abandoned_carts_public_insert on public.abandoned_carts;
create policy abandoned_carts_public_insert
  on public.abandoned_carts for insert
  to anon, authenticated
  with check (true);

drop policy if exists abandoned_carts_public_update on public.abandoned_carts;
create policy abandoned_carts_public_update
  on public.abandoned_carts for update
  to anon, authenticated
  using (true)
  with check (true);


-- ─── 4. Cupom aplicado em orders ──────────────────────────────────
alter table public.orders
  add column if not exists coupon_code text,
  add column if not exists discount_amount numeric(12,2) not null default 0;

create index if not exists orders_coupon_code_idx
  on public.orders (coupon_code) where coupon_code is not null;
