-- ════════════════════════════════════════════════════════════════════
-- Phase 3 — Retenção via email marketing
--
-- Cria a infra de:
--   1. email_subscribers — lista única com double opt-in (regra D1)
--   2. email_sent_log    — idempotência da sequência pós-compra +
--                          reativação + carrinho abandonado (regra D3)
--
-- Não cria tabela de "newsletters enviadas em massa" — sazonais ficam
-- como envio manual (admin ou Resend Broadcast direto). Aqui o foco é
-- automação por evento (compra, abandono, inatividade).
-- ════════════════════════════════════════════════════════════════════

-- ─── 1. Subscribers (newsletter) ──────────────────────────────────
create table if not exists public.email_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  confirmed boolean not null default false,
  confirmation_token text not null,
  confirmation_sent_at timestamptz not null default now(),
  confirmed_at timestamptz,
  -- Token estável usado em todos os emails para 1-click unsubscribe (D2).
  -- Não muda nem quando o usuário se reinscreve — fica vinculado ao email.
  unsubscribe_token text not null,
  unsubscribed_at timestamptz,
  source text not null default 'unknown', -- 'footer', 'checkout', 'admin', etc.
  attribution_data jsonb not null default '{}'::jsonb,
  -- Tags computadas (cliente_ativo, recorrente, vip, inativo_*, por categoria)
  -- atualizadas pelo cron de segmentação.
  tags jsonb not null default '[]'::jsonb,
  tags_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists email_subscribers_email_lower_idx
  on public.email_subscribers (lower(email));

create unique index if not exists email_subscribers_confirmation_token_idx
  on public.email_subscribers (confirmation_token);

create unique index if not exists email_subscribers_unsubscribe_token_idx
  on public.email_subscribers (unsubscribe_token);

create index if not exists email_subscribers_confirmed_idx
  on public.email_subscribers (confirmed) where confirmed = true;

drop trigger if exists email_subscribers_set_updated_at on public.email_subscribers;
create trigger email_subscribers_set_updated_at
  before update on public.email_subscribers
  for each row execute function public.set_updated_at();

-- RLS: anon NÃO lê nem lista. Insert é via backend que valida email
-- (rate limit + double opt-in). Update/select só pelo backend.
alter table public.email_subscribers enable row level security;
-- Sem policies = sem acesso para anon. Service role bypassa.


-- ─── 2. Log de emails enviados (idempotência) ─────────────────────
-- Cada envio automático grava aqui ANTES de chamar o SMTP — se algo
-- falhar, o reenvio na próxima execução do cron vê o registro e pula.
--
-- Estratégia de chave:
--   (email, kind, entity_id) é único.
--   - kind = 'post_purchase_d3' / 'post_purchase_d15' / 'post_purchase_d45'
--           / 'abandoned_cart_1h' / 'abandoned_cart_24h'
--           / 'reactivation_90d'
--           / 'opt_in_confirmation' / 'unsubscribe_success'
--           / 'order_confirmation'
--   - entity_id = order_id, abandoned_cart_id, subscriber_id (depende do kind)
create table if not exists public.email_sent_log (
  id bigint generated by default as identity primary key,
  email text not null,
  kind text not null,
  entity_id text,
  status text not null default 'queued' check (status in ('queued','sent','failed','skipped')),
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists email_sent_log_dedup_idx
  on public.email_sent_log (lower(email), kind, coalesce(entity_id, ''));

create index if not exists email_sent_log_kind_created_idx
  on public.email_sent_log (kind, created_at desc);

alter table public.email_sent_log enable row level security;
-- Sem policies = só service_role acessa.


-- ─── 3. Política de retenção do log (90 dias) ─────────────────────
create or replace function public.cleanup_old_email_logs()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  deleted_count integer := 0;
begin
  with deleted as (
    delete from public.email_sent_log
    where created_at < now() - interval '90 days'
    returning 1
  )
  select count(*) into deleted_count from deleted;
  return deleted_count;
end;
$$;

revoke execute on function public.cleanup_old_email_logs() from public;
revoke execute on function public.cleanup_old_email_logs() from anon;
revoke execute on function public.cleanup_old_email_logs() from authenticated;


-- ─── 4. Helper: gera tokens aleatórios criptograficamente seguros ─
-- pgcrypto vem ativo por padrão em Supabase, mas garantimos.
create extension if not exists pgcrypto;
