-- ════════════════════════════════════════════════════════════════════
-- Phase 2 — Tabela de eventos de segurança
--
-- Coletor para eventos como:
--   • webhook_invalid_signature (assinatura HMAC do MP inválida)
--   • admin_login_failed       (tentativa de login admin com creds erradas)
--   • verify_payment_email_mismatch (enumeração de order_code)
--
-- RLS habilitada, SEM policies → só service_role enxerga. Mesma estratégia
-- de download_logs/settings (docs/SECURITY.md §3).
--
-- Retenção: incluída em purge_old_logs() — 6 meses (mais sensível que
-- download_logs porque guarda IP + UA de atacantes potenciais).
-- Idempotente.
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  severity text not null default 'warn',  -- info | warn | error
  ip text,
  user_agent text,
  request_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_events_event_created_idx
  on public.security_events (event_name, created_at desc);

create index if not exists security_events_ip_idx
  on public.security_events (ip, created_at desc)
  where ip is not null;

create index if not exists security_events_created_at_idx
  on public.security_events (created_at desc);

alter table public.security_events enable row level security;
-- Sem policies — service role bypassa, anon/authenticated não enxergam.

comment on table public.security_events is
  'Eventos de segurança (HMAC inválido, login admin falho, enumeração). Service role only.';


-- ─── Estende purge_old_logs para incluir security_events (6 meses) ───
-- Drop necessário porque o tipo de retorno mudou (3 colunas em vez de 2).
drop function if exists public.purge_old_logs();

create function public.purge_old_logs()
returns table (
  download_logs_deleted bigint,
  analytics_events_deleted bigint,
  security_events_deleted bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_download_count bigint := 0;
  v_analytics_count bigint := 0;
  v_security_count bigint := 0;
begin
  -- download_logs > 12 meses
  with deleted as (
    delete from public.download_logs
    where downloaded_at < (now() - interval '12 months')
    returning 1
  )
  select count(*) into v_download_count from deleted;

  -- analytics_events > 24 meses (se a tabela existir)
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'analytics_events'
  ) then
    with deleted as (
      delete from public.analytics_events
      where created_at < (now() - interval '24 months')
      returning 1
    )
    select count(*) into v_analytics_count from deleted;
  end if;

  -- security_events > 6 meses
  with deleted as (
    delete from public.security_events
    where created_at < (now() - interval '6 months')
    returning 1
  )
  select count(*) into v_security_count from deleted;

  return query select v_download_count, v_analytics_count, v_security_count;
end;
$$;

revoke execute on function public.purge_old_logs() from public, anon, authenticated;
